name 'repository'
version '0.1.6'
maintainer 'AJ Christensen'
maintainer_email 'aj@junglist.io'
license 'Apache 2.0'
description 'Build repos. Uses nginx. Use repoman or metarepo.'

depends 'nginx', '= 2.0.0'
depends 'apt'
depends 'gpg', '>= 0.2.2'
